routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//-----------------------------------------------------------------
// Authentication
//-----------------------------------------------------------------

// Auth routes
Route::auth();

Route::get('zabudnute/heslo', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('forgot.password.index');
Route::post('zabudnute/heslo', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('forgot.password.email');
Route::get('heslo/reset', 'Auth\PasswordController@showResetForm')->name('forgot.password.reset');
Route::post('heslo/reset', 'Auth\ResetPasswordController@reset')->name('forgot.password.reset.password');

// Register route
Route::get('register', 'Site\RegisterController@index')->name('register.index');

// Socialite auth
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider')->name('provider.login.or.sync');
Route::get('auth/{provider}/callback','Auth\AuthController@handleProviderCallback');

//-----------------------------------------------------------------
// Courses
//-----------------------------------------------------------------

// Courses routes
Route::get('predmet/matematika','Site\HomeController@math')->name('math');
Route::get('predmet/anglictina','Site\HomeController@english')->name('english');

//-----------------------------------------------------------------
// Settings
//-----------------------------------------------------------------

Route::get('uzivatel/nastavenia', 'Site\UserController@index')->name('user.index');

//-----------------------------------------------------------------
// Site routes
//-----------------------------------------------------------------

Route::get('/', 'Site\HomeController@index')->name('index');
Route::get('/nova', 'Site\HomeController@nova')->name('nova');

//-----------------------------------------------------------------
// Lektor controller
//-----------------------------------------------------------------

Route::get('/portal', 'Lector\LectorController@index')->name('lector.index');
Route::get('/portal/matematika', 'Site\LectorController@math')->name('site.lector.math');
Route::get('/portal/anglictina', 'Site\HomeController@english')->name('site.lector.english');
Route::get('/portal/francuzstina', 'Site\HomeController@french')->name('site.lector.french');

//-----------------------------------------------------------------
// Resource routes ..
//-----------------------------------------------------------------

//-----------------------------------------------------------------
// Api routes
//-----------------------------------------------------------------

// TODO Kvoli tomu, aby som mohol robit request cez POSTMANA, tak som docasne vypol authentifikaciu ..
Route::group(['prefix' => 'api', 'as' => 'api.',/* 'middleware' => ['auth']*/], function () {
    Route::resource('subject', 'Api\SubjectController');
    Route::resource('course', 'Api\CourseController');
    Route::resource('lesson', 'Api\LessonController');
    Route::resource('module', 'Api\ModuleController');
    Route::resource('section', 'Api\SectionController');

    // Vimeo
    Route::get('/vimeo/albums', 'Api\VimeoController@getAlbums');
    Route::get('/vimeo/albums/{albumID}/videos', 'Api\VimeoController@getVideosInAlbum');
    Route::get('/vimeo/albums/name/{name}', 'Api\VimeoController@getAlbumByName');

    // Route::get('{lesson}', 'Api\LessonController@getByCode');   //TODO Vyzera byt ako catchall, prerobit, zachytava metody, ktore nechcem ..
});

//----------------------------------------------------------
// Admin routes
//----------------------------------------------------------

// Admin routes
Route::group(['prefix' => 'administrator', 'as' => 'administrator.', 'middleware' => ['auth', 'admin']], function () {

    // Home route
    Route::get('/','Admin\ArticleController@index')->name('index');

    // Article routes
    Route::get('article/archive', 'Admin\ArticleController@listarchive')->name('article.archive.index');
    Route::post('article/{article}/archive/archive', 'Admin\ArticleController@archive')->name('article.archive.archive');
    Route::post('article/{article}/archive/restore', 'Admin\ArticleController@restore')->name('article.archive.restore');
    Route::resource('article', 'Admin\ArticleController');

    // Trash routes
    Route::get('trash', 'Admin\TrashController@index')->name('trash.index');
    Route::post('trash/{item}/restore', 'Admin\TrashController@restore')->name('trash.restore');
    Route::delete('trash/{item}/destroy', 'Admin\TrashController@destroy')->name('trash.destroy');

    // Category routes
    Route::resource('category', 'Admin\CategoryController');

    // Settings routes
    Route::resource('settings', 'Admin\SettingsController');

    // User routes
    Route::resource('user', 'Admin\UserController');

});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Interfaces\ITrashable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model implements ITrashable
{

    use SoftDeletes;

    protected $table = 'tbl_d_article';

    protected $appends = ['intro_text'];

    protected $dates = ['deleted_at'];

    /*************************************************************
     * Relations
     *************************************************************/

    public function author()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function status()
    {
        return $this->belongsTo('App\Status', 'status_id');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'tbl_r_article_category');
    }

    /*************************************************************
     * Accessor definitions
     *************************************************************/

    /**
     * Returns the portion of article_text before READMORE placeholder
     * @return mixed
     */
    public function getIntroTextAttribute()
    {
        if (strpos($this->article_text, config('javascript.tinymce.readmore')) > 0) {
            return explode('<p>'.config('javascript.tinymce.readmore').'</p>',$this->article_text)[0];
        } else {
            return $this->article_text;
        }
    }

    /**
     * Returns the full article text without the placeholders such as 'READMORE'
     * @return mixed Remove readmore text from the string ..
     */
    public function getArticleTextParsedAttribute()
    {
        return str_replace(config('javascript.tinymce.readmore'),'', $this->article_text);
    }

    /*************************************************************
     * Model methods
     *************************************************************/

    /**
     * Get all articles in a specified category
     * @param null $categoryCode
     * @return mixed
     */
    // TODO $categoryId should be a collection ..
    public static function getArticles(int $categoryId = null, int $statusID = 2, int $isTrash = 0, int $isArchive = 0)
    {
        $result = \DB::table('tbl_d_article')
            ->leftJoin('tbl_r_article_category', 'tbl_d_article.id', '=', 'tbl_r_article_category.article_id');

        if (!empty($categoryId)) {
            $result->where('tbl_r_article_category.category_id', '=', $categoryId);
        }

        if (!empty($statusID)) {
            $result->where('status_id', '=', $statusID);
        }

        if ($isTrash) {
            $result->whereNotNull('deleted_at');
        } else {
            $result->whereNull('deleted_at');
        }

//        var_dump($result->where('archive' ,'=', $isArchive)
//            ->orderBy('start_publishing', 'desc')->toSql());
//        exit;

        $result->where('archive' ,'=', $isArchive)
            ->orderBy('start_publishing', 'desc');

        return Article::hydrate($result->get()->toArray());

//        ($isTrash) ? $result =  $result->withTrashed()->get() : $result =  $result->onlyTrashed()->get();
//            $result->where('trash' ,'=', $isTrash)
//                    ->where('archive' ,'=', $isArchive)
//                    ->orderBy('start_publishing', 'desc')->get()
        //);
    }

    /**
     * Get articles in the archive
     * @return mixed
     */
    public static function getArchivedArticles()
    {
        return Article::where('archive', 1)->orderBy('created_at','desc')->get();
    }



    // TODO Ako sa robi archivacia? Pouzivam este stlpce 'archived', 'trash'? Robim predsa softdelete, takze ak nepouzivam
    // stlpec trash, musim ho zmazat z DB



    /*************************************************************
     * Trash interface implementations
     *************************************************************/

    /**
     * @return mixed The name of the article visible in the trash
     */
    public function trashTitle()
    {
        return $this->title;
    }

    /**
     * @return string Document type visible in the trash
     */
    public function trashDocumentType()
    {
        return 'Article';
    }

    /**
     * @return mixed The date, when was the article trashed ..
     */
    public function trashedAt()
    {
        return $this->deleted_at;
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;


class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (Gate::forUser(Auth::user())->allows('view-dashboard')) {
            $articles = Article::getArticles(null, 0);
            return view('admin.article.index', ['articles' => $articles]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.article.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'title' => 'required',
            'alias' => 'required',
        ]);

        // Save article
        $article = new Article();
        $this->saveArticle($request, $article);

        // Save article categories
        $article->categories()->attach((array) $request->input('categories'));

        // Return the result
        return response()->json(['result' => true]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        return view('admin.article.edit', ['article' => $article]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title' => 'required',
            'alias' => 'required',
        ]);

        $article = Article::find($id);
        $this->saveArticle($request, $article);

        // Add / remove related categories ..
        $article->categories()->sync((array) $request->input('categories'));

        $request->session()->flash('status', 'Article was successfully saved!');

        if ($request->get('action') == 'save') {
            return redirect()->route('administrator.article.edit', ['article' => $article]);
        } elseif ($request->get('action') == 'save_and_close') {
            return redirect()->route('administrator.article.index');
        }

    }

    /**
     * Move the article into the trash
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, int $id)
    {

        try {

            $article = Article::find($id);
            $article->delete();

            return response()->json(['result' => true]);

        } catch(Exception $e) {
            $msg = 'An error occured: ';
            return response()->json(['result' => false, 'message' => $msg.$e->getMessage()]);
        }

    }

    /**
     * Move many articles into the trash at once ..
     * @param Request $request
     * @param array $ids Article IDs you want to trash
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroyMany(Request $request, array $ids)
    {
        try {

            foreach ($ids as $id) {
                $article = Article::find($id);
                $article->delete();
            }

            return response()->json(['result' => true]);

        } catch (Exception $e) {
            $msg = 'An error occured: ';
            return response()->json(['result' => false, 'message' => $msg.$e->getMessage()]);
        }
    }

    // Archive methods

    /**
     * Archive the article
     * @param $id
     * @return mixed
     */
    public function archive($id)
    {
        $article = Article::find($id);
        $article->archive = 1;
        $article->save();

        return response()->json(['result' => true]);
    }

    /**
     * List articles in the archive
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function listArchive(Request $request)
    {
        $currentURL = $request->path();
        $articles = Article::getArchivedArticles();
        return view('admin.article.index', ['articles' => $articles, 'currentURL' => $currentURL]);
    }

    /**
     * Unarchive the article ..
     * @param $id
     * @return mixed
     */
    public function restore($id)
    {
        $article = Article::find($id);
        $article->archive = 0;
        $article->save();

        return response()->json(['result' => true]);
    }

    // Delete methods

    /**
     * Delete the article completelly from the database
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function wipe($id)
    {
        $article = Article::find($id);
        $article->delete();

        return response()->json(['result' => true]);
    }

    /**
     * @param Request $request
     * @param $article
     */
    protected function saveArticle(Request $request, $article)
    {
        $article->title = $request->input('title');
        $article->alias = $request->input('alias');
        $article->article_text = $request->input('article_text');
//        $article->status_id = $request->input('status');
        $article->user_id = 1;
        $article->start_publishing = $request->input('start_publishing');
        $article->finish_publishing = $request->input('finish_publishing');
        $article->save();
    }


}

resources/views/admin/article/actions.blade.php
<div class="btn-group">
    <button id="actions_container_{{ $article->id }}" type="button" class="btn btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: transparent;">
        <span class="fa fa-ellipsis-v" style="font-size: 1.5em; color: grey;"></span>
    </button>
    <ul class="dropdown-menu">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        {{--TODO Fix redirects here, they need to be dynamic--}}
        @if (in_array(url()->getRequest()->path(), config()->get('custom.action_buttons.archive')))
            <li><a href="{{ route('administrator.article.archive.archive', $article->id) }}" data-redirect="{{ route('administrator.article.index') }}" data-method="delete" class="jquery-postback"><span class="fa fa-archive"></span>Archive</a></li>
        @endif
        @if (in_array(url()->getRequest()->path(), config()->get('custom.action_buttons.trash')))
            <li><a href="{{ route('administrator.article.destroy', $article->id) }}" data-redirect="{{ route('administrator.article.index') }}" data-method="delete" class="jquery-postback"><span id="trash_{{ $article->id }}" class="fa fa-trash"></span>Trash</a></li>
        @endif
        @if (in_array(url()->getRequest()->path(), config()->get('custom.action_buttons.restore')))
            <li><a href="{{ route('administrator.article.archive.restore', $article->id) }}" data-redirect="{{ route('administrator.article.archive.index') }}" class="jquery-postback"><span class="fa fa-recycle"></span>Restore</a></li>
        @endif
        @if (in_array(url()->getRequest()->path(), config()->get('custom.action_buttons.wipe')))
            <li><a href="{{ route('administrator.trash.wipe', $article->id) }}" data-redirect="{{ route('administrator.trash.index') }}" data-method="delete" class="jquery-postback"><span class="fa fa-trash"></span>Completely delete</a></li>
        @endif
    </ul>
</div>

resources/views/admin/article/edit.blade.php
@extends('admin.layouts.main')
@section('content')

    {{--Open form--}}

    <?php if (isset($article)) { ?>
        {{ Form::model($article, ['id' => 'article-form', 'route' => ['administrator.article.update', $article->id]]) }}
    <?php } else { ?>
        {{ Form::open(['id' => 'article-form', 'url' => '/administrator/article']) }}
    <?php } ?>

    <input type="hidden" name="article_id" value="{{ isset($article->id) ? $article->id : '' }}">

    {{--Toolbar--}}

    <div class="toolbar">
        <button id="article_save_and_close" name="action" value="save_and_close" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save & Close</button>
        <button id="article_save" name="action" value="save" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save</button>
        <a id="form-close" href="#" class="btn btn-danger btn-sm" data-redirect="/administrator/article"><i class="fa fa-close"></i> Close</a>
    </div>

    {{--Status & error messages--}}

    @include('admin.common.message')

    {{--Content--}}

    <div class="content">

        <div class="box box-default">

            <div class="box-header with-border">
                <h3 class="box-title">Article edit</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">

                <div class="row">
                    <div class="col-md-8">
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <label>Title:</label>
                                    <?php echo Form::text('title', null, ['class' => 'form-control']); ?>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Alias:</label>
                                    <?php echo Form::text('alias', null, ['class' => 'form-control']); ?>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Article text:</label>
                            <?php echo Form::textarea('article_text', null, ['id' => 'article_text', 'class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="col-md-4">

                        <div class="form-group">
                            <label>Status:</label>
                            <?php
                                $status_id = isset($article->status->id) ? $article->status->id : '';
                                echo Form::select('status', App\Status::pluck('name','status_id'), $status_id, ['class' => 'chosen-select']);
                            ?>
                        </div>

                        <div class="form-group">
                            <label>Categories:</label>
                            <?php
                                if (isset($article)) {
                                    $categories = $article->categories()->get()->pluck('id')->toArray();
                                } else {
                                    $categories = [];
                                }
                                echo Form::select('categories[]', App\Category::all()->pluck('name','id'), $categories, ['id' => 'categories','multiple']);
                            ?>

                        </div>

                        <div class="form-group">
                            <label>Start publishing:</label>

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <?php
                                    $start_publishing = !empty($article->start_publishing) ? null : \Carbon\Carbon::now()->toDateTimeString();
                                    echo Form::datetime('start_publishing', $start_publishing, ['id' => 'start_publishing', 'class' => 'form-control']);
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Finish publishing:</label>

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <?php
                                    $finish_publishing = !empty($article->finish_publishing) ? null : \Carbon\Carbon::now()->addYears(10)->toDateTimeString();
                                    echo Form::datetime('finish_publishing', $finish_publishing, ['id' => 'finish_publishing', 'class' => 'form-control']);
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Date updated:</label>

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <?php
                                    $updated_at = !empty($article->updated_at) ? null : \Carbon\Carbon::now()->toDateTimeString();
                                    echo Form::datetime('updated_at', $updated_at, ['disabled', 'id' => 'updated_at', 'class' => 'form-control']);
                                ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Date created:</label>

                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <?php
                                    $created_at = !empty($article->created_at) ? null : \Carbon\Carbon::now()->toDateTimeString();
                                    echo Form::datetime('created_at', $created_at, ['disabled', 'id' => 'created_at', 'class' => 'form-control']);
                                ?>
                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>
    </div>

    {{ Form::close() }}

    <form style="display:none" id="fileUploadForm" method="post">
        <input id="juraj" type="hidden" name="_token" value="{{ csrf_token() }}" >
        <input id="fileUploader" type="file" name="fileUpload"  />
    </form>

@endsection

resources/views/admin/article/index.blade.php
<?php use Illuminate\Support\Facades\Route; ?>
@extends('admin.layouts.main')
@section('content')

{{-- Toolbar --}}

<div class="toolbar">
    <a id="new_article" href="/administrator/article/create" class="btn btn-success btn-sm"><span class="fa fa-plus-circle"></span> New article</a>
</div>

{{--Status & error messages--}}

@include('admin.common.message')

{{--Content--}}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header">
                    <h3 class="box-title">Articles</h3>
                </div>

                <div class="box-body">

                    <?php

                    (Route::getFacadeRoot()->current()->uri() === 'administrator/article/archive') ? $idName = "dt-archive" : $idName = "dt-articles";

                    ?>

                    <table id={{ $idName }} class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            {{--<th class="select-checkbox"></th>--}}
                            <th></th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Category</th>
                            <th>Status</th>
                            <th>Updated</th>
                            <th>Created</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Category</th>
                            <th>Status</th>
                            <th>Updated</th>
                            <th>Created</th>
                        </tr>
                        </tfoot>
                        <tbody>
                            @foreach($articles as $article)
                                <tr id="{{ $article->id }}">
                                    <td></td>
                                    <td>
                                        <a href="/administrator/article/{{ $article->id }}/edit">{{ $article->title }}</a><br/>
                                        <div class="text-sm">Alias: &nbsp;
                                            {{ $article->alias }}
                                        </div>
                                    </td>
                                    <td>
                                        <div class="flex-container">
                                            <div>
                                                {{ $article->author->name }}
                                            </div>
                                        </div>
                                    </td>
                                    <td>{{ ($article->categories->count() > 0) ? $article->categories->first()->name : "-" }}</td>
                                    <td style="text-align: center;">
                                        <?php echo isset($article->status->name) & $article->status->name === 'Published' ? '1' :  '2'  ?>
                                    </td>
                                    <td>{{ $article->updated_at }}</td>
                                    <td>{{ $article->created_at }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

<!-- Control Sidebar -->
{{--@include('admin.common.right-menu')--}}