routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//-----------------------------------------------------------------
// Authentication
//-----------------------------------------------------------------

// Auth routes
Route::auth();

Route::get('zabudnute/heslo', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('forgot.password.index');
Route::post('zabudnute/heslo', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('forgot.password.email');
Route::get('heslo/reset', 'Auth\PasswordController@showResetForm')->name('forgot.password.reset');
Route::post('heslo/reset', 'Auth\ResetPasswordController@reset')->name('forgot.password.reset.password');

// Register route
Route::get('register', 'Site\RegisterController@index')->name('register.index');

// Socialite auth
Route::get('auth/{provider}', 'Auth\AuthController@redirectToProvider')->name('provider.login.or.sync');
Route::get('auth/{provider}/callback','Auth\AuthController@handleProviderCallback');

//-----------------------------------------------------------------
// Courses
//-----------------------------------------------------------------

// Courses routes
Route::get('predmet/matematika','Site\HomeController@math')->name('math');
Route::get('predmet/anglictina','Site\HomeController@english')->name('english');

//-----------------------------------------------------------------
// Settings
//-----------------------------------------------------------------

Route::get('uzivatel/nastavenia', 'Site\UserController@index')->name('user.index');

//-----------------------------------------------------------------
// Site routes
//-----------------------------------------------------------------

Route::get('/', 'Site\HomeController@index')->name('index');
Route::get('/nova', 'Site\HomeController@nova')->name('nova');

//-----------------------------------------------------------------
// Lektor controller
//-----------------------------------------------------------------

Route::get('/portal', 'Lector\LectorController@index')->name('lector.index');
Route::get('/portal/matematika', 'Site\LectorController@math')->name('site.lector.math');
Route::get('/portal/anglictina', 'Site\HomeController@english')->name('site.lector.english');
Route::get('/portal/francuzstina', 'Site\HomeController@french')->name('site.lector.french');

//-----------------------------------------------------------------
// Resource routes ..
//-----------------------------------------------------------------

//-----------------------------------------------------------------
// Api routes
//-----------------------------------------------------------------

// TODO Kvoli tomu, aby som mohol robit request cez POSTMANA, tak som docasne vypol authentifikaciu ..
Route::group(['prefix' => 'api', 'as' => 'api.',/* 'middleware' => ['auth']*/], function () {
    Route::resource('subject', 'Api\SubjectController');
    Route::resource('course', 'Api\CourseController');
    Route::resource('lesson', 'Api\LessonController');
    Route::resource('module', 'Api\ModuleController');
    Route::resource('section', 'Api\SectionController');

    // Vimeo
    Route::get('/vimeo/albums', 'Api\VimeoController@getAlbums');
    Route::get('/vimeo/albums/{albumID}/videos', 'Api\VimeoController@getVideosInAlbum');
    Route::get('/vimeo/albums/name/{name}', 'Api\VimeoController@getAlbumByName');

    // Route::get('{lesson}', 'Api\LessonController@getByCode');   //TODO Vyzera byt ako catchall, prerobit, zachytava metody, ktore nechcem ..
});

//----------------------------------------------------------
// Admin routes
//----------------------------------------------------------

// Admin routes
Route::group(['prefix' => 'administrator', 'as' => 'administrator.', 'middleware' => ['auth', 'admin']], function () {

    // Home route
    Route::get('/','Admin\ArticleController@index')->name('index');

    // Article routes
    Route::get('article/archive', 'Admin\ArticleController@listarchive')->name('article.archive.index');
    Route::post('article/{article}/archive/archive', 'Admin\ArticleController@archive')->name('article.archive.archive');
    Route::post('article/{article}/archive/restore', 'Admin\ArticleController@restore')->name('article.archive.restore');
    Route::resource('article', 'Admin\ArticleController');

    // Trash routes
    Route::get('trash', 'Admin\TrashController@index')->name('trash.index');
    Route::post('trash/{item}/restore', 'Admin\TrashController@restore')->name('trash.restore');
    Route::delete('trash/{item}/destroy', 'Admin\TrashController@destroy')->name('trash.destroy');

    // Category routes
    Route::resource('category', 'Admin\CategoryController');

    // Settings routes
    Route::resource('settings', 'Admin\SettingsController');

    // User routes
    Route::resource('user', 'Admin\UserController');

});

app/User.php
<?php

namespace App;

use App\Interfaces\ITrashable;
use App\Http\Traits\Auth\Roles;
use Illuminate\Support\Facades\Auth;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements ITrashable
{

    protected $table = 'tbl_d_user';

    protected $primaryKey = 'user_id';

    use SoftDeletes;
    use CanResetPassword;
    use Notifiable;
    use Roles;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'status_id', 'avatar', 'gender'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $dates = ['deleted_at'];

    /******************************************************************************
     * Relations
     ******************************************************************************/

    public function socialProviders()
    {
        return $this->hasMany('App\SocialProvider', 'user_id');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'tbl_r_user_role');
    }

    /******************************************************************************
     * Trash methods
     ******************************************************************************/

    public function trashTitle()
    {
        return $this->first_name;
    }

    public function trashDocumentType()
    {
        return 'User';
    }

    public function trashedAt()
    {
        $this->deleted_at;
    }

    /******************************************************************************
     * Model methods
     ******************************************************************************/

    public function getNameAttribute()
    {
        return $this->first_name. ' '. $this->last_name;
    }

    /******************************************************************************
     * Model methods
     ******************************************************************************/

    public function isAdmin()
    {
        // TODO Toto by uz fungovat nemalo .. Pouzivam role ..
        return Auth::user()->is_admin == 1;
    }

    public function isActiveStatus()
    {
        return Auth::user()->status_id == 10;
    }

    public function updateUser($user, UserRequest $request)
    {
        return  $user->update([
            'first_name'  => $request->first_name,
            'last_name' => $request->last_name,
            'email' => $request->email,
            'is_subscribed' => $request->is_subscribed,
            'is_admin' => $request->is_admin,
            'status_id' => $request->status_id,
        ]);
    }

    public function showAdminStatusOf($user)
    {
        return $user->is_admin ? 'Yes' : 'No';
    }

    public function showNewsletterStatusOf($user)
    {
        return $user->is_subscribed == 1 ? 'Yes' : 'No';
    }

    public function widgets()
    {
        return $this->hasMany('App\Widget');
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => ['required', 'email'],
            'password' => 'required'
        ]);

        $user = new User();
        return $this->saveUser($request, $user);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.user.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => ['required', 'email']
        ]);

        $user = User::findOrFail($id);
        return $this->saveUser($request, $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, int $id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        if ($request->ajax()) {
            return response()->json(['result' => true]);
        } else {
            return view('admin.user.index');
        }

    }

    /**
     * @param Request $request
     * @param $user
     * @return \Illuminate\Http\RedirectResponse
     */
    protected function saveUser(Request $request, $user)
    {

        try {
            $user->first_name = $request->input('first_name');
            $user->last_name = $request->input('last_name');
            $user->email = $request->input('email');
            $user->password = $request->input('password');
            $user->roles()->sync($request->input('roles'));
            $user->save();
        } catch (Exception $e) {
            return redirect()->back()->withErrors([$e->getMessage()]);
        }

        $request->session()->flash('status', 'User successfully saved.');

        if ($request->get('action') == 'save') {
            return redirect()->route('administrator.user.edit', ['user' => $user]);
        } elseif ($request->get('action') == 'save_and_close') {
            return redirect()->route('administrator.user.index');
        }
    }
}

app/Http/Controllers/Site/UserController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Http\Request;
use App\Http\Controllers\Site\Controller;

class UserController extends Controller
{

    /**
     * Zobraz stranku s nastaveniami pre uzivatela ..
     */
    public function index()
    {
        return view('site.pages.settings.index');
    }

}

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.main')
@section('content')

    {{--Open form--}}

    <?php if (isset($user)) { ?>
    {{ Form::model($user, ['id' => 'user-form'/*, 'route' => ['administrator.user.update', $user->user_id]*/]) }}
    <?php } else { ?>
    {{ Form::open(['id' => 'user-form', 'url' => '/administrator/user']) }}
    <?php } ?>

    {{--Hidden fields--}}

    <input type="hidden" name="user_id" value="{{ isset($user->user_id) ? $user->user_id : '' }}">

    {{--Toolbar--}}

    <div class="toolbar">
        <button id="user_save_and_close" name="action" value="save_and_close" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save & Close</button>
        <button id="user_save" name="action" value="save" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save</button>
        <a id="form-close" href="#" class="btn btn-danger btn-sm" data-redirect="{{ route('administrator.user.index') }}"><i class="fa fa-close"></i> Close</a>
    </div>

    {{--Status & error messages--}}

    @include('admin.common.message')

    {{--Content--}}

    <div class="content">

        <div class="box box-default">

            <div class="box-header with-border">
                <h3 class="box-title">User form</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i>
                    </button>
                </div>
            </div>

            <div class="box-body">

                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>First name:</label>
                            <?php echo Form::text('first_name', null, ['class' => 'form-control']); ?>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Last name:</label>
                            <?php echo Form::text('last_name', null, ['class' => 'form-control']); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Email:</label>
                            <?php echo Form::text('email', null, ['class' => 'form-control']); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Password:</label>
                            <?php echo Form::password('password', ['class' => 'form-control']); ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Roles:</label>
                            <?php
                            if (isset($user)) {
                                $roles = $user->roles()->get()->pluck('role_id')->toArray();
                            } else {
                                $roles = [];
                            }
                            echo Form::select('roles[]', App\Role::all()->pluck('name','role_id'), $roles, ['id' => 'roles','multiple']);
                            ?>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    {{ Form::close() }}

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.main')
@section('content')

{{-- Toolbar --}}

<div class="toolbar">
    <a href="{{ route('administrator.user.create') }}" class="btn btn-success btn-sm"><span class="fa fa-plus-circle"></span> New user</a>
</div>

{{--Status & error messages--}}

@include('admin.common.message')

{{--Content--}}

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-danger">
                <div class="box-header">
                    <h3 class="box-title">User list</h3>
                </div>

                <div class="box-body">
                    <table id="dt-users" class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Updated</th>
                            <th>Created</th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr id="{{ $user->user_id }}">
                                    <td>{{ $user->user_id }}</td>
                                    <td><a href="{{ route('administrator.user.edit', $user->user_id) }}">{{ $user->name }}</a></td>
                                    <td>{{ $user->updated_at }}</td>
                                    <td>{{ $user->created_at }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection